version: 2
jobs:
  build:
    working_directory: ~/mean-starter
    docker:
      - image: circleci/node:6.14.4-stretch-browsers
      - image: mongo:latest
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: sudo npm install node-sass -g 
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
