version: 2
jobs:
  build:
    working_directory: ~/mean-starter
    docker:
      - image: circleci/node:6.14.4-stretch-browsers
      - image: mongo:latest
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:     
          name: test
          command: npm test

